name: CI/CD

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: "gradle"

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "build/libs/*.jar"
          target: "/home/${{ secrets.EC2_USER }}/app"

      - name: Restart app on EC2
        uses: appleboy/ssh-action@v1.1.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            set -e
            APP_DIR="/home/${{ secrets.EC2_USER }}/app"
            mkdir -p "$APP_DIR"
            LATEST_JAR=$(ls -t $APP_DIR/*.jar | head -n1)
            ln -sf "$LATEST_JAR" "$APP_DIR/app.jar"
            if pgrep -f "$APP_DIR/app.jar" > /dev/null; then
              pkill -f "$APP_DIR/app.jar"
              sleep 2
            fi
            nohup java -jar "$APP_DIR/app.jar" --server.port=8080 > "$APP_DIR/app.log" 2>&1 &
